name: persistent_bottom_nav_bar
description: A do all, highly customizable persistent/static bottom navigation bar for flutter. Includes up-to 20 styles.

homepage: https://github.com/BilalShahid13/PersistentBottomNavBar
repository: https://github.com/BilalShahid13/PersistentBottomNavBar
version: 4.0.2

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
